const STATUS_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

const AUTH_EXCLUDED_PATHS = new Set([
  '/api/v1/auth/signin',
  '/api/v1/auth/signup',
  '/api/v1/auth/forgot-password',
  '/api/v1/auth/verify-reset-password-otp',
]);

const PERMISSIONS = {
  // Tenant management
  UPDATE_TENANT: 'UPDATE_TENANT',

  // User Management
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_USERS: 'VIEW_USERS',
  DELETE_USERS: 'DELETE_USERS',
  CREATE_USERS: 'CREATE_USERS',
  UPDATE_USERS: 'UPDATE_USERS',
  VIEW_LIST_USERS: 'VIEW_LIST_USERS',

  // Role Management
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_ROLES: 'VIEW_ROLES',
  DELETE_ROLES: 'DELETE_ROLES',
  CREATE_ROLES: 'CREATE_ROLES',
  UPDATE_ROLES: 'UPDATE_ROLES',
  VIEW_LIST_ROLES: 'VIEW_LIST_ROLES',

  // Task Management
  MANAGE_TASKS: 'MANAGE_TASKS',
  VIEW_TASKS: 'VIEW_TASKS',
  DELETE_TASKS: 'DELETE_TASKS',
  CREATE_TASKS: 'CREATE_TASKS',
  UPDATE_TASKS: 'UPDATE_TASKS',
  VIEW_LIST_TASKS: 'VIEW_LIST_TASKS',

  // Project Management
  MANAGE_PROJECTS: 'MANAGE_PROJECTS',
  VIEW_PROJECTS: 'VIEW_PROJECTS',
  DELETE_PROJECTS: 'DELETE_PROJECTS',
  CREATE_PROJECTS: 'CREATE_PROJECTS',
  UPDATE_PROJECTS: 'UPDATE_PROJECTS',
  VIEW_LIST_PROJECTS: 'VIEW_LIST_PROJECTS',
};

export { STATUS_CODES, AUTH_EXCLUDED_PATHS, PERMISSIONS };
