const STATUS_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

const AUTH_EXCLUDED_PATHS = new Set([
  '/api/v1/auth/signin',
  '/api/v1/auth/signup',
  '/api/v1/auth/forgot-password',
  '/api/v1/auth/reset-password',
  '/api/v1/auth/me',
  '/api/v1/auth/accept-invitation',
]);

const PERMISSIONS = {
  // Tenant management
  UPDATE_TENANT: 'UPDATE_TENANT',

  // User Management
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_LIST_USERS: 'VIEW_LIST_USERS',
  VIEW_TEAM_STATS: 'VIEW_TEAM_STATS',

  // Role Management
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_LIST_ROLES: 'VIEW_LIST_ROLES',

  // Task Management
  MANAGE_TASKS: 'MANAGE_TASKS',
  VIEW_TASKS: 'VIEW_TASKS',
  DELETE_TASKS: 'DELETE_TASKS',
  CREATE_TASKS: 'CREATE_TASKS',
  UPDATE_TASKS: 'UPDATE_TASKS',
  VIEW_LIST_TASKS: 'VIEW_LIST_TASKS',

  // Project Management
  MANAGE_PROJECTS: 'MANAGE_PROJECTS',
  VIEW_PROJECTS: 'VIEW_PROJECTS',
  DELETE_PROJECTS: 'DELETE_PROJECTS',
  CREATE_PROJECTS: 'CREATE_PROJECTS',
  UPDATE_PROJECTS: 'UPDATE_PROJECTS',
  VIEW_LIST_PROJECTS: 'VIEW_LIST_PROJECTS',
};

const PERMISSIONS_LIST = [
  'VIEW_LIST_USERS',
  'VIEW_LIST_ROLES',
  'MANAGE_TASKS',
  'VIEW_TASKS',
  'DELETE_TASKS',
  'CREATE_TASKS',
  'UPDATE_TASKS',
  'VIEW_LIST_TASKS',
  'MANAGE_PROJECTS',
  'VIEW_PROJECTS',
  'DELETE_PROJECTS',
  'CREATE_PROJECTS',
  'UPDATE_PROJECTS',
  'VIEW_LIST_PROJECTS',
];

export { STATUS_CODES, AUTH_EXCLUDED_PATHS, PERMISSIONS, PERMISSIONS_LIST };
